### ISSUE TITLE
Error when `npm start`

### ISSUE THREAD

**Issue by UkonnRa** [innFactory/create-react-app-material-typescript-redux#3]
Just follow the commands, and get an error:
```
Starting the development server...

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: no space left on device, watch '/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/public'
    at FSWatcher.start (internal/fs/watchers.js:161:26)
    at Object.watch (fs.js:1227:11)
    at createFsWatchInstance (/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:159:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/node_modules/chokidar/index.js:257:10)
    at createFsWatchInstance (/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/nickluo/Workspaces/PythonWorkspace/create-react-app-material-typescript-redux/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:159:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-react-app-material-typescript-redux@0.0.1 start: `react-scripts-ts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the create-react-app-material-typescript-redux@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nickluo/.npm/_logs/2018-07-27T07_12_21_797Z-debug.log
```

**Comment by UkonnRa** [comment]
`df` for disk usage info:
```
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             8146644       12   8146632   1% /dev
tmpfs            1631892     1276   1630616   1% /run
/dev/nvme0n1p2 223316572 43480912 168468800  21% /
none                   4        0         4   0% /sys/fs/cgroup
none                5120        0      5120   0% /run/lock
none             8159452   320852   7838600   4% /run/shm
none              102400       72    102328   1% /run/user
/dev/nvme0n1p1    523248     3240    520008   1% /boot/efi
```

**Comment by spoeck** [comment]
@CasterKKK 
Thanks for the issue. Unfortunately I can't reproduce it.
Maybe it helps to increase the amount of watchers:
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
